### ISSUE TITLE
Feature suggestion; Dual-purpose keys

### ISSUE THREAD

**Issue by jonqrandom** [MuddledGuy/ToggleSneak#1]
what i mean is that your keys could act either as toggles (when tapped for less than a configurable number of milliseconds/ticks) or operate with vanilla behaviour if held for longer. that way a player could remap them to LCTRL and LSHIFT and easily access both behaviours without taking up two more _(preciousssssss)_ keybinds ;)

**Comment by MuddledGuy** [comment]
This mod was never made to be updated unless there was a bug with it, you may clone it and add your own features, I just updated and fixed the mod for 1.12.2

**Comment by MuddledGuy** [comment]
To add on to this, this has been tested with a configurable delay, however, there are conflicts with the default sprint/sneak keybinds. Unless someone else would like to work on this, it will not be added.
