### ISSUE TITLE
Sprint Doesn't Work

### ISSUE THREAD

**Issue by NPCtom** [MuddledGuy/ToggleSneak#2]
Sprint combination does not work. Also when is there another update?

**Comment by MuddledGuy** [comment]
What version are you using? You cannot use Sneak & Sprint at the same time.

**Comment by NPCtom** [comment]
My apologies. My error.

**Comment by MuddledGuy** [comment]
Sorry for the late response, I would also like to explain why this will not be added either. I am trying to keep this compliant with most PvP/Factions server's rules, and that means you can't sprint while sneaking.
